### ISSUE TITLE
Stuck on fetching

### ISSUE THREAD

**Issue by thgilciffart** [TheRiceCold/dots#9]
Each time Ive tried to apply its been stuck on fetching forever and ive let it sit and to no avail

**Comment by thgilciffart** [comment]
I think I forgot abt formatting will try manual method then update you

**Comment by TheRiceCold** [comment]
> Each time Ive tried to apply its been stuck on fetching forever and ive let it sit and to no avail

I'm sorry, but where are you stuck with? is it during `nix-switch`?

**Comment by thgilciffart** [comment]
Hi, I managed to successfully install however I fail to boot, when I'm prompted with the kaizen login screen, it resembles the minimal install where I just have the terminal. When I build the system via ```sudo nixos-install --flake .#kaizen```, the root account fails to start Hyprland with the error of being logged in as a superuser and using the flag ```i am really stupid``` flag. However when I run it with ```sudo nixos-install ----no-root-passwd --flake .#kaizen``` it fails too

**Comment by thgilciffart** [comment]
for quick comms add me on discord via ```jarjar.binks``` as i don't have github mobile

**Comment by thgilciffart** [comment]
Wait I didn't correctly read abt nix-switch part,etc. I will retry now

**Comment by thgilciffart** [comment]
nvm i dont know how to do nix switch gives me no cmd error

**Comment by thgilciffart** [comment]
I switched over to EndeavourOS for now
